# Site settings
title: My Cyberpunk Vault
description: A whimsical cyberpunk twist on my Obsidian notes
url: "https://<your-username>.github.io"
baseurl: "/<your-repo-name>"  # leave empty ("") if publishing from the root domain

# Theme
remote_theme: ziinahzoor/cybersynth-theme  
plugins:
  - jekyll-remote-theme

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation (if supported by the theme)
# adjust to match your folder structure
nav:
  - Home: index.md
  - Projects: projects.md
  - Notes: notes/index.md

# Exclude Obsidian-specific junk
exclude:
  - .obsidian
  - .obsidian/**
  - Gemfile
  - Gemfile.lock

# Include any asset folders you reference directly
include:
  - images
